backend:
  name: github
  repo: tu-usuario-de-github/ctp-la-suiza  # <--- CAMBIA esto por tu usuario real y el nombre de tu repositorio
  branch: main

media_folder: "img"
public_folder: "/img"

collections:
  - name: "contenido"
    label: "Páginas Web"
    files:
      - file: "index.html"
        label: "Página Principal"
        name: "index"
        fields:
          - { label: "Título Principal (Hero)", name: "hero_title", widget: "string", default: "Informática y Redes" }
          - { label: "Descripción (Hero)", name: "hero_desc", widget: "text" }
